# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-03 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='city',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='description',
            new_name='lasr_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
    ]
